name: CI

on:
  workflow_dispatch:
  pull_request:
    branches: ["main"]
  push:
    branches: ["restore-from-codex"]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12", "3.13"]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install pytest pytest-asyncio ruff mypy

      - name: Lint (ruff)
        run: ruff check .

      - name: Type check (mypy)
        run: mypy --config-file mypy.ini .

      - name: Run tests
        run: pytest -q
