name: CI

on:
  workflow_dispatch:
  pull_request:
    branches: ["main"]
  push:
    branches: ["restore-from-codex"]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
          cache: "pip"
          cache-dependency-path: |
            requirements.txt
            mypy.ini

      - name: Upgrade pip tooling
        run: python -m pip install --upgrade pip setuptools wheel

      - name: Install ALL project dependencies
        run: pip install -r requirements.txt

      - name: Install dev tools (tests, lint, types)
        run: pip install pytest pytest-asyncio ruff mypy

      - name: Show key package versions
        run: |
          python -V
          python -c "import torch, sklearn, httpx; print('torch =', getattr(torch, '__version__', '?')); print('sklearn =', getattr(sklearn, '__version__', '?')); print('httpx =', getattr(httpx, '__version__', '?'))"

      - name: Lint (ruff)
        run: ruff check .

      - name: Type check (mypy)
        run: mypy --config-file mypy.ini .

      - name: Run tests
        env:
          # На GitHub-раннере нет GPU; выключаем, чтобы не пыталось инициализировать CUDA.
          CUDA_VISIBLE_DEVICES: ""
        run: |
          pytest -q
